---
title:  |  
  |  *Multivariate Analysis for the Behavioral Sciences,*
  |  Second Edition (Chapman and Hall/CRC, 2019)
  |  **Exercises of Chapter 15:**
  |  **Exploratory Factor Analysis**
author: "Kimmo Vehkalahti and Brian S. Everitt"
date: "14 December 2018"
output: 
  pdf_document:
    number_sections: no
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercises

## Exercise 15.4

Use the matrix R below, modifying the related R code given in the **Examples of Chapter 15**.

```{r}
R <- c(
        1.00,-0.04, 0.61, 0.45, 0.03,-0.29,-0.30, 0.45, 0.30,
       -0.04, 1.00,-0.07,-0.12, 0.49, 0.43, 0.30,-0.31,-0.17,
        0.61,-0.07, 1.00, 0.59, 0.03,-0.13,-0.24, 0.59, 0.32,
        0.45,-0.12, 0.59, 1.00,-0.08,-0.21,-0.19, 0.63, 0.37,
        0.03, 0.49, 0.03,-0.08, 1.00, 0.47, 0.41,-0.14,-0.24,
       -0.29, 0.43,-0.13,-0.21, 0.47, 1.00, 0.63,-0.13,-0.15,
       -0.30, 0.30,-0.24,-0.19, 0.41, 0.63, 1.00,-0.26,-0.29,
        0.45,-0.31, 0.59, 0.63,-0.14,-0.13,-0.26, 1.00, 0.40,
        0.30,-0.17, 0.32, 0.37,-0.24,-0.15,-0.29, 0.40, 1.00
      )
R <- matrix(R, ncol = 9, byrow = TRUE)
R
```
