---
title:  |  
  |  *Multivariate Analysis for the Behavioral Sciences,*
  |  Second Edition (Chapman and Hall/CRC, 2019)
  |  **Solutions to Exercises of Chapter 17:**
  |  **Cluster Analysis**
author: "Kimmo Vehkalahti and Brian S. Everitt"
date: "19 December 2018"
output: 
  pdf_document:
    number_sections: no
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Solutions

# Exercise 17.3

```{r, fig.width=6, fig.height=6}
lowtemp <- structure(
  c(-8, -7, -44, -12, -27, 4, -25, -8, 53, 12, -22, 23, 30, -17, -6, -23, 17, -26, -16, 24, 
    0, -5, 26, 20, -12, 16, 7, 30, -2, 23, 57, 31, 6, 39, 46, 23, 12, 5, 32, 8, 13, 31, 29, 
    24, 53, 51, 35, 54, 40, 59, 43, 57, 67, 62, 36, 49, 69, 51, 52, 44, 61, 40, 33, 43, 43, 
    55, 28, 25, 5, 28, 17, 29, 3, 25, 64, 33, 11, 41, 51, 26, 28, 13, 34, 15, 8, 34, 28, 29),
.Dim = c(22L, 4L), .Dimnames = list(c("Atlanta", "Baltimore", "Bismark", "Boston", "Chicago", 
                   "Dallas", "Denver", "El Paso", "Honolulu", "Houston", "Juneau", "Los Angeles", 
                   "Miami", "Nashville", "New York", "Omaha", "Phoenix", "Portland", "Reno", 
                   "San Francisco", "Seattle", "Washington"), 
                 c("January", "April", "July", "October")))
lowtemp

pairs(lowtemp)
```
\pagebreak
```{r}
lowtemp_pc <- princomp(lowtemp)
xlim <- range(lowtemp_pc$scores[, 1])
plot(lowtemp_pc$scores[, 1:2], ylim = xlim)
# possibly 2 or three clusters?
```
\pagebreak
```{r}
lowtemp_km2 <- kmeans(lowtemp, 2)
lowtemp_km2
```
\pagebreak
```{r}
lowtemp_km3 <- kmeans(lowtemp, 3)
lowtemp_km3
```
\pagebreak
```{r}
par(mfrow = c(1,2))
plot(lowtemp_pc$scores[, 1:2], ylim = xlim, type = "n")
text(lowtemp_pc$scores[, 1:2], labels = as.numeric(lowtemp_km2$cluster), cex=0.8)

plot(lowtemp_pc$scores[, 1:2], ylim = xlim, type = "n")
text(lowtemp_pc$scores[, 1:2], labels = as.numeric(lowtemp_km3$cluster), cex=0.8)
```

Try also other methods!

\pagebreak

## Exercise 17.5

```{r}
protein <- read.table("data/protein.txt", sep = '\t', header = TRUE)
head(protein)

protein_pc <- princomp(protein)
xlim <- range(protein_pc$scores[, 1])
plot(protein_pc$scores[, 1:2], ylim = xlim)
# possibly 2 clusters?

```

Try some agglomerative methods and plot solutions in PC space.

\pagebreak

