---
title:  |  
  |  *Multivariate Analysis for the Behavioral Sciences,*
  |  Second Edition (Chapman and Hall/CRC, 2019)
  |  **Solutions to Exercises of Chapter 12:**
  |  **Multivariate Data and Multivariate Analysis**
author: "Kimmo Vehkalahti and Brian S. Everitt"
date: "28 November 2018"
output: 
  pdf_document:
    number_sections: no
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Solutions

## Exercise 12.3

**Source of the data**: Keyfitz, N. and Flieger, W. (1971). *Population: The Facts and Methods of Demography.* W. H. Freeman, San Francisco, California.

```{r, echo=TRUE}
life71 <- structure(list(
  
  m0 = c(63, 34, 38, 59, 56, 62, 50, 65, 56, 69, 65, 64, 56, 60, 61, 49, 
         59, 63, 59, 65, 65, 64, 64, 67, 61, 68, 67, 65, 59, 58, 57), 
  m25 = c(51, 29, 30, 42, 38, 44, 39, 44, 46, 47, 48, 50, 44, 44, 45, 40, 
          42, 44, 44, 48, 48, 63, 43, 45, 40, 46, 45, 46, 43, 44, 46), 
  m50 = c(30, 13, 17, 20, 18, 24, 20, 22, 24, 24, 26, 28, 25, 22, 22, 22, 
          22, 23, 24, 28, 26, 21, 21, 23, 21, 23, 23, 24, 23, 24, 28), 
  m75 = c(13, 5, 7, 6, 7, 7, 7, 7, 11, 8, 9, 11, 10, 6, 8, 9, 6, 8, 8, 14, 
          9, 7, 6, 8, 10, 8, 8, 9, 10, 9, 9), 
  
  w0 = c(67, 38, 38, 64, 62, 69, 55, 72, 63, 75, 68, 66, 61, 65, 65, 51, 
         61, 67, 63, 68, 67, 68, 68, 74, 67, 75, 74, 71, 66, 62, 60), 
  w25 = c(54, 32, 34, 46, 46, 50, 43, 50, 54, 53, 50, 51, 48, 45, 49, 41, 43, 
        48, 46, 51, 49, 47, 47, 51, 46, 52, 51, 51, 49, 47, 49), 
  w50 = c(34, 17, 20, 25, 25, 28, 23, 27, 33, 29, 27, 29, 27, 25, 27, 23, 22,
        26, 25, 29, 27, 25, 24, 28, 25, 29, 28, 28, 27, 25, 28), 
  w75 = c(15, 6, 7, 8, 10, 14, 8, 9, 19, 10, 10, 11, 12, 9, 10, 8, 7, 9, 8, 
        13, 10, 9, 8, 10, 11, 10, 10, 10, 12, 10, 11)), 
  
  class = "data.frame", 
  
  .Names = c("m0", "m25", "m50", "m75", "w0", "w25", "w50", "w75"),

  row.names = c("Algeria", "Cameroon", "Madagascar", "Mauritius", "Reunion",
              "Seychelles", "South Africa(C)", "South Africa(W)", "Tunisia", 
              "Canada", "Costa Rica", "Dominican Rep", "El Salvador", "Greenland", 
              "Grenada", "Guatemala", "Honduras", "Jamaica", "Mexico", "Nicaragua", 
              "Panama", "Trinidad(62)", "Trinidad (67)", "United States (66)", 
              "United States (NW66)", "United States (W66)", "United States (67)", 
              "Argentina", "Chile", "Columbia", "Ecuador"))

head(life71, n = 12)
tail(life71, n = 12)

# get summary statistics for men and for women
Rmen <- cor(life71[, 1:4])
Smen <- var(life71[, 1:4])
mean_men <- apply(life71[, 1:4], 2, mean)

Rwomen <- cor(life71[,5:8])
Swomen <- var(life71[,5:8])
mean_women <- apply(life71[, 5:8], 2, mean)
```
\pagebreak
```{r, echo=TRUE, fig.width=4, fig.height=4}
pairs(life71[, 1:4])
pairs(life71[, 5:8])

pairs(life71[, 1:4], panel = function(x,y) text(x, y, abbreviate(row.names(life71)), cex=0.5))

pairs(life71[, 5:8], panel = function(x,y) text(x, y, abbreviate(row.names(life71)), cex=0.5))

```
\pagebreak
```{r, echo=TRUE}
attach(life71)
par(mfrow = c(1,2))
plot(m0, m75, xlab = "Life expectation at birth", 
     ylab = "Life expectation at age 75", type = "n", ylim = c(5, 16), xlim = c(30, 80))
text(m0, m75, abbreviate(row.names(life71)), cex=0.6)
title("Men")

plot(w0, w75, xlab = "Life expectation at birth", 
     ylab = "Life expectation at age 75", type = "n", ylim = c(5, 16), xlim = c(30, 80))
text(w0, w75, abbreviate(row.names(life71)), cex=0.6)

title("Women")

detach(life71)
```
