---
title:  |  
  |  *Multivariate Analysis for the Behavioral Sciences,*
  |  Second Edition (Chapman and Hall/CRC, 2019)
  |  **Examples of Chapter 8:**
  |  **Analysis of Longitudinal Data I: Graphical Displays and Summary Measure Approach**
author: "Kimmo Vehkalahti and Brian S. Everitt"
date: "1 October 2018"
output: 
  pdf_document:
    number_sections: no
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\pagebreak

# Examples

# Table 8.1: BPRS Measurements from 40 Subjects

```{r}
library(tidyr); library(dplyr); library(ggplot2)

BPRS <- read.table("data/BPRS.txt", sep = ' ', header = TRUE)
BPRS <- within(BPRS, {
    treatment <- factor(treatment)
      subject <- factor(subject)
})

glimpse(BPRS)
head(BPRS)
tail(BPRS)

# Convert data to long form:
BPRSL <- gather(BPRS, key = weeks, value = bprs, week0:week8) %>%
  mutate(week = as.integer(substr(weeks, 5, 5)))

glimpse(BPRSL)
head(BPRSL)
tail(BPRSL)
```
\pagebreak

## Figure 8.1

```{r}
p1 <- ggplot(BPRSL, aes(x = week, y = bprs, linetype = subject))
p2 <- p1 + geom_line() + scale_linetype_manual(values = rep(1:10, times=4))
p3 <- p2 + facet_grid(. ~ treatment, labeller = label_both)
p4 <- p3 + theme_bw() + theme(legend.position = "none")
p5 <- p4 + theme(panel.grid.minor.y = element_blank())
p6 <- p5 + scale_y_continuous(limits = c(min(BPRSL$bprs), max(BPRSL$bprs)))
p6
```
\pagebreak

## Figure 8.2

```{r}
# Standardise the scores:
BPRSL <- BPRSL %>%
  group_by(week) %>%
  mutate( stdbprs = (bprs - mean(bprs))/sd(bprs) ) %>%
  ungroup()
glimpse(BPRSL)

p1 <- ggplot(BPRSL, aes(x = week, y = stdbprs, linetype = subject))
p2 <- p1 + geom_line() + scale_linetype_manual(values = rep(1:10, times=4))
p3 <- p2 + facet_grid(. ~ treatment, labeller = label_both)
p4 <- p3 + theme_bw() + theme(legend.position = "none")
p5 <- p4 + theme(panel.grid.minor.y = element_blank())
p6 <- p5 + scale_y_continuous(name = "standardized bprs")
p6
```
\pagebreak

## Figure 8.3

```{r}
# Number of weeks, baseline (week 0) included:
n <- BPRSL$week %>% unique() %>% length()

# Make a summary data:
BPRSS <- BPRSL %>%
  group_by(treatment, week) %>%
  summarise( mean=mean(bprs), se=sd(bprs)/sqrt(n) ) %>%
  ungroup()
glimpse(BPRSS)

p1 <- ggplot(BPRSS, aes(x = week, y = mean, linetype = treatment, shape = treatment))
p2 <- p1 + geom_line() + scale_linetype_manual(values = c(1,2))
p3 <- p2 + geom_point(size=3) + scale_shape_manual(values = c(1,2))
p4 <- p3 + geom_errorbar(aes(ymin=mean-se, ymax=mean+se, linetype="1"), width=0.3)
p5 <- p4 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p6 <- p5 + theme(legend.position = c(0.8,0.8))
p7 <- p6 + scale_y_continuous(name = "mean(bprs) +/- se(bprs)")
p7
```
\pagebreak

## Figure 8.4

```{r}
p1 <- ggplot(BPRSL, aes(x = factor(week), y = bprs, fill = treatment))
p2 <- p1 + geom_boxplot(position = position_dodge(width = 0.9))
p3 <- p2 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p4 <- p3 + theme(legend.position = c(0.8,0.8))
p5 <- p4 + scale_x_discrete(name = "week")
# Black & White version:
#p6 <- p5 + scale_fill_grey(start = 0.5, end = 1)
p5
```
\pagebreak

## Figure 8.5

```{r}
# Make a summary data of the post treatment weeks (1-8)
BPRSL8S <- BPRSL %>%
  filter(week > 0) %>%
  group_by(treatment, subject) %>%
  summarise( mean=mean(bprs) ) %>%
  ungroup()

glimpse(BPRSL8S)

p1 <- ggplot(BPRSL8S, aes(x = treatment, y = mean))
p2 <- p1 + geom_boxplot()
p3 <- p2 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p4 <- p3 + stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white")
p5 <- p4 + scale_y_continuous(name = "mean(bprs), weeks 1-8")
p5
```
\pagebreak

## Figure 8.6

```{r}
# Remove the outlier:
BPRSL8S1 <- BPRSL8S %>%
  filter(mean < 60)

glimpse(BPRSL8S1)

p1 <- ggplot(BPRSL8S1, aes(x = treatment, y = mean))
p2 <- p1 + geom_boxplot()
p3 <- p2 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p4 <- p3 + stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white")
p5 <- p4 + scale_y_continuous(name = "mean(bprs), weeks 1-8")
p5
```
\pagebreak

## Table 8.3

```{r}
# Without the outlier, apply Student's t-test, two-sided:

t.test(mean ~ treatment, data = BPRSL8S1, var.equal = TRUE)
```
\pagebreak

## Table 8.4

```{r}
# Add the baseline from the original data as a new variable to the summary data:

baseline <- BPRS$week0
BPRSL8S2 <- BPRSL8S %>%
  mutate(baseline)

# Fit the ANCOVA model and see the results:

fit <- lm(mean ~ baseline + treatment, data = BPRSL8S2)

summary(fit)
anova(fit)
```
\pagebreak

# Table 8.5: Pain Scores from 83 Women in Labor: 43 Subjects in Group 1 (Medication) and 40 Subjects in Group 2 (Placebo)
```{r}
PAIN <- read.table("data/pain.txt", header = TRUE, sep = "\t")

PAIN <- within(PAIN, {
    group <- factor(group)
       id <- factor(id)
})

glimpse(PAIN)
```
\pagebreak

## Table 8.6

```{r}
# Convert data to long form:
PAINL <- gather(PAIN, key = mins, value = pain, -group, -id) %>%
  mutate(mins = as.integer(substr(mins,2,4)))

glimpse(PAINL)

# (1) Make a summary data of group means,
# removing subjects with any missing values:

PAINLS1 <- PAINL %>%
  group_by(group, id) %>%
  summarise( mean=mean(pain) ) %>%
  ungroup()

glimpse(PAINLS1)

# (2) Make a summary data of group means,
# now using the mean of available responses for each subject:

PAINLS2 <- PAINL %>%
  group_by(group, id) %>%
  summarise( mean=mean(pain, na.rm = TRUE) ) %>%
  ungroup()

glimpse(PAINLS2)

# Compare the t-test results:

t.test(mean ~ group, data = PAINLS1, var.equal = TRUE)
t.test(mean ~ group, data = PAINLS2, var.equal = TRUE)
```
